
server:
  port: 8888

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.game.po
  configuration:
    map-underscore-to-camel-case: true

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countsql

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/game?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    name: root
    password: 123456
  thymeleaf:
        prefix: classpath:/templates/
        suffix: .html

#¥Ú”°sql”Ôæ‰
logging:
  level:
    com.example.game.dao: debug
